# Generated by Django 4.0.6 on 2022-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0002_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
