# Generated by Django 4.0.6 on 2022-07-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0003_alter_register_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='phone_number',
        ),
    ]
