# Generated by Django 4.0.6 on 2022-08-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0008_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_user',
        ),
    ]
