# Generated by Django 4.0.6 on 2022-08-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0009_delete_register_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images')),
                ('slug', models.CharField(max_length=400)),
                ('detail', models.TextField()),
                ('specs', models.TimeField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.size')),
            ],
        ),
    ]
