# Generated by Django 4.0.6 on 2022-08-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moontag_app.size')),
            ],
        ),
    ]
