# Generated by Django 4.0.6 on 2022-08-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0011_banner_remove_product_price_alter_product_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='media/brand_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='media/category_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='media/product_images'),
        ),
    ]
