# Generated by Django 4.0.6 on 2022-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0018_alter_productattribute_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='img',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
