# Generated by Django 4.0.6 on 2022-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0021_remove_product_img_productattribute_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='clom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clom1', models.CharField(max_length=200)),
                ('clom2', models.CharField(max_length=200)),
            ],
        ),
    ]
