# Generated by Django 4.0.6 on 2022-08-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0022_clom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clom',
            options={'verbose_name_plural': '8. Product clom'},
        ),
    ]
