# Generated by Django 4.0.6 on 2022-08-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0023_alter_clom_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clom',
            old_name='clom1',
            new_name='title',
        ),
    ]
