# Generated by Django 4.0.6 on 2022-08-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0024_rename_clom1_clom_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clom',
        ),
    ]
