# Generated by Django 4.0.6 on 2022-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0027_alter_cartorder_options_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Product Review'},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
