# Generated by Django 4.0.6 on 2022-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0029_alter_productreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
