# Generated by Django 4.0.6 on 2022-11-01 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moontag_app', '0031_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('store_img', models.ImageField(null=True, upload_to='media/store_images')),
                ('business_email', models.EmailField(max_length=254)),
                ('pay_pal', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
