# Generated by Django 4.0.6 on 2022-11-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0032_storeregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeregister',
            options={'verbose_name_plural': '10. Vendors'},
        ),
    ]
