# Generated by Django 4.0.6 on 2022-11-01 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moontag_app', '0033_alter_storeregister_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreRegister',
            new_name='Vendors',
        ),
        migrations.AlterModelOptions(
            name='vendors',
            options={'verbose_name_plural': '11. Vendors'},
        ),
    ]
