# Generated by Django 4.0.6 on 2022-11-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0035_aaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aaa',
        ),
    ]
