# Generated by Django 4.0.6 on 2022-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0036_delete_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='store_img',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='user',
        ),
    ]
