# Generated by Django 4.0.6 on 2022-11-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0037_remove_vendors_store_img_remove_vendors_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
