# Generated by Django 4.0.6 on 2022-11-07 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moontag_app', '0041_vendorproduct_delete_vendoraddproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorProduct',
            new_name='VendorAddProduct',
        ),
    ]
