# Generated by Django 4.0.6 on 2022-11-10 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moontag_app', '0042_rename_vendorproduct_vendoraddproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': 'A10. Product Review'},
        ),
        migrations.AlterModelOptions(
            name='vendoraddproduct',
            options={'verbose_name_plural': 'A13. Vendors Products'},
        ),
        migrations.AlterModelOptions(
            name='vendors',
            options={'verbose_name_plural': 'A12. Vendors'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'A11. Wishlist'},
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'A14. Todo',
            },
        ),
    ]
